### ISSUE TITLE
linux下开ss，股票小助手会崩溃。

### ISSUE THREAD

**Issue by zzugyl** [pentie/stock-viewer#1]
linux下开ss，股票小助手会崩溃。
原版也会崩溃。

**Comment by boypt** [comment]
这个跟chrome有关吧，插件其实就是个简单网页。
对了我这个版本也在商店上架了。

**Comment by franky-liu** [comment]
Chrome商店的小工具挺好用的，但是我关注的一只基金“519697”无法显示价格和涨幅，能否有时间更新下？

**Comment by boypt** [comment]
场外基金不进行实时交易，没有交易数据的，部分软件提供的“实时估值”实际上是根据基金财报公布的前10持仓的涨跌幅权重运算，仅有参考价值。

目前没有公开接口能做这个数据。

franky-liu <notifications@github.com> 于 2018年10月8日周一 11:47写道：
